version: "3.7"

services:
  elasticsearch:
    container_name: mall-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: mall-kibana
    image: docker.elastic.co/kibana/kibana:6.8.7
    ports:
      - 5601:5601

  logtash:
    container_name: mall-logtash
    image: docker.elastic.co/logstash/logstash:6.8.7
    ports:
      - 9600:9600
